### PR TITLE
eclipse/rdf4j#1197 tests don't support and even block support for gra…

### PR DESCRIPTION
**Pull request by hmottestad**
This PR addresses GitHub issue: eclipse/rdf4j#1197 .

Briefly describe the changes proposed in this PR:

* ignore tests that block graph support in reasoner

### CODE REVIEW

**Comment by hmottestad** [comment]
Would also like to say that splitting tests into a separate git repo means that rerunning the tests takes around 5 minutes, because I have to first mvn install the testsuites and then mvn clean install the storage repo to be able to rerun a test. Serious pain.

**Comment by jeenbroekstra** [comment]
Why aren't you fixing this by ignoring/overriding these tests in your concrete test class, rather than in the generic suite?

**Comment by hmottestad** [comment]
Good point @jeenbroekstra. I will try to find out where these tests are being called. Probably somewhere in the storage repo.

**Comment by jeenbroekstra** [comment]
If fixing it locally succeeds I guess we can close this PR for now? FWIW I think it's worth revisiting some of these tests but this particular change seems unnecessary for the moment.

**Comment by hmottestad** [comment]
I've pushed changes where i override the tests in the storage repo, so let's wait to see that I've done everything correctly there (jenkins builds) before we close and delete this branch.

**Comment by hmottestad** [comment]
fixed locally

**Pull request closed without merging**
